replicaCount: 1

image:
  repository: ricardoschmg/miapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

containerPort: 8080

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false