apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miapp
  template:
    metadata:
      labels:
        app: miapp
    spec:
      containers:
        - name: miapp
          image: ricardoschmg/miapp:latest
          ports:
            - containerPort: 8080